# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\zeindevs\Documents\ZEN\CODING\python-scripts-tools\videoplayer\ui\videocontrol.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VideoControl(object):
    def setupUi(self, VideoControl):
        VideoControl.setObjectName("VideoControl")
        VideoControl.resize(547, 45)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VideoControl.sizePolicy().hasHeightForWidth())
        VideoControl.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(VideoControl)
        self.gridLayout.setContentsMargins(6, 6, 6, 6)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.playButton = QtWidgets.QPushButton(VideoControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playButton.sizePolicy().hasHeightForWidth())
        self.playButton.setSizePolicy(sizePolicy)
        self.playButton.setMinimumSize(QtCore.QSize(0, 25))
        self.playButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.playButton.setObjectName("playButton")
        self.horizontalLayout.addWidget(self.playButton)
        self.labelPosition = QtWidgets.QTextEdit(VideoControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPosition.sizePolicy().hasHeightForWidth())
        self.labelPosition.setSizePolicy(sizePolicy)
        self.labelPosition.setMinimumSize(QtCore.QSize(0, 0))
        self.labelPosition.setMaximumSize(QtCore.QSize(70, 25))
        self.labelPosition.setReadOnly(True)
        self.labelPosition.setObjectName("labelPosition")
        self.horizontalLayout.addWidget(self.labelPosition)
        self.positionSlider = QtWidgets.QSlider(VideoControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.positionSlider.sizePolicy().hasHeightForWidth())
        self.positionSlider.setSizePolicy(sizePolicy)
        self.positionSlider.setOrientation(QtCore.Qt.Horizontal)
        self.positionSlider.setObjectName("positionSlider")
        self.horizontalLayout.addWidget(self.positionSlider)
        self.labelDuration = QtWidgets.QTextEdit(VideoControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDuration.sizePolicy().hasHeightForWidth())
        self.labelDuration.setSizePolicy(sizePolicy)
        self.labelDuration.setMinimumSize(QtCore.QSize(0, 0))
        self.labelDuration.setMaximumSize(QtCore.QSize(70, 25))
        self.labelDuration.setReadOnly(True)
        self.labelDuration.setObjectName("labelDuration")
        self.horizontalLayout.addWidget(self.labelDuration)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(VideoControl)
        QtCore.QMetaObject.connectSlotsByName(VideoControl)

    def retranslateUi(self, VideoControl):
        _translate = QtCore.QCoreApplication.translate
        VideoControl.setWindowTitle(_translate("VideoControl", "Form"))
        self.playButton.setText(_translate("VideoControl", "Play"))
        self.labelPosition.setHtml(_translate("VideoControl", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">00:00:00</p></body></html>"))
        self.labelDuration.setHtml(_translate("VideoControl", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">00:00:00</p></body></html>"))
